

services:
  backend:
    build: ./flask-backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    env_file:
      - ./flask-backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./express-frontend
      args:
        API_URL: "http://flask-backend:5000"   # ✅ this will be available during build
    container_name: express-frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://flask-backend:5000       # ✅ this will be available at runtime
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
