version: '3.9'

services:
  backend:
    build: ./flask-backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    env_file:
      - ./flask-backend/.env
    networks:
      - app-network

  frontend:
    build: ./express-frontend
    container_name: express-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
